[tool.black]
line-length = 120
extend-exclude = """
/(
  | build
  | dist
  | .poetry
)/
"""
target-version = ["py310"]

[tool.flake8]
inline-quotes = "double"
ignore = "E203, W503, S101, D100, D104"
max-line-length = 120
docstring-convention = "google"
extend-exclude = ".venv, build, dist, migrations, .poetry"
per-file-ignores = [
    "tests/*: D"
]

[tool.isort]
profile = "black"
default_section = "THIRDPARTY"
force_single_line = true
line_length = 120
use_parentheses = true
py_version=310

[tool.mypy]
ignore_missing_imports = true
follow_imports = "silent"
warn_redundant_casts = true
warn_unused_ignores = false
check_untyped_defs = true
no_implicit_reexport = true
show_error_codes = true
exclude = """
(^|/)(\\.venv|build|dist|migrations|\\.poetry)(/|$)
"""

[bandit]
exclude = "tests, .poetry"
skips = "B101, B601"
