name: Keep Render Service Awake

on:
  schedule:
    - cron: '*/5 * * * *'  # هر ۵ دقیقه یکبار
  workflow_dispatch:       # امکان اجرای دستی از GitHub

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Service
        run: curl -f https://golden-tma-backend.onrender.com || exit 1
